// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'pilgrim.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_Pilgrim _$PilgrimFromJson(Map<String, dynamic> json) => _Pilgrim(
  profileId: json['profileId'] as String?,
  displayName: json['displayName'] as String?,
  fieldStatus: json['fieldStatus'] as String?,
  medicalTestStatus: json['medicalTestStatus'] as String?,
  travelDate: json['travelDate'] == null
      ? null
      : DateTime.parse(json['travelDate'] as String),
  hotelName: json['hotelName'] as String?,
  hotelLocationUrl: json['hotelLocationUrl'] as String?,
  transportationDetails: json['transportationDetails'] as String?,
  travelPermitNumber: json['travelPermitNumber'] as String?,
  id: (json['id'] as num?)?.toInt(),
  koboId: json['koboId'] as String?,
  enrollmentId: json['enrollmentId'] as String?,
  pilgrimId: json['pilgrimId'] as String?,
  tripId: json['tripId'] as String?,
  tripType: json['tripType'] as String?,
  groupId: json['groupId'] as String?,
  sequence: json['sequence'] as String?,
  cluster: json['cluster'] as String?,
  coordinatorName: json['coordinatorName'] as String?,
  stickerNumber: json['stickerNumber'] as String?,
  visaNumber: json['visaNumber'] as String?,
  barcodeNumber: json['barcodeNumber'] as String?,
  fullNameAr: json['fullNameAr'] as String?,
  motherNameAr: json['motherNameAr'] as String?,
  birthDate: json['birthDate'] as String?,
  firstNameEn: json['firstNameEn'] as String?,
  lastNameEn: json['lastNameEn'] as String?,
  fatherNameEn: json['fatherNameEn'] as String?,
  motherNameEn: json['motherNameEn'] as String?,
  passportNumber: json['passportNumber'] as String?,
  passportExpiryDate: json['passportExpiryDate'] as String?,
  passportIssueDate: json['passportIssueDate'] as String?,
  gender: json['gender'] as String?,
  bodySize: json['bodySize'] as String?,
  groupName: json['groupName'] as String?,
  companionName: json['companionName'] as String?,
  relation: json['relation'] as String?,
  requestType: json['requestType'] as String?,
  housingType: json['housingType'] as String?,
  hadyStatus: json['hadyStatus'] as String?,
  residence: json['residence'] as String?,
  healthStatus: json['healthStatus'] as String?,
  needsWheelchair: json['needsWheelchair'] as bool?,
  isSmoking: json['isSmoking'] as bool?,
  healthCard: json['healthCard'] as bool?,
  isVaccinated: json['isVaccinated'] as bool?,
  makkahHotel: json['makkahHotel'] as String?,
  makkahFloor: json['makkahFloor'] as String?,
  makkahRoom: json['makkahRoom'] as String?,
  madinahTravelDate: json['madinahTravelDate'] as String?,
  madinahHotel: json['madinahHotel'] as String?,
  madinahFloor: json['madinahFloor'] as String?,
  madinahRoom: json['madinahRoom'] as String?,
  departureAirport: json['departureAirport'] as String?,
  departureAirline: json['departureAirline'] as String?,
  departureFlightNo: json['departureFlightNo'] as String?,
  departureDate: json['departureDate'] as String?,
  departureTime: json['departureTime'] as String?,
  returnAirport: json['returnAirport'] as String?,
  returnAirline: json['returnAirline'] as String?,
  returnFlightNo: json['returnFlightNo'] as String?,
  returnDate: json['returnDate'] as String?,
  returnTime: json['returnTime'] as String?,
  serviceCenterName: json['serviceCenterName'] as String?,
  serviceCenterArafat: json['serviceCenterArafat'] as String?,
  serviceCenterMina: json['serviceCenterMina'] as String?,
  busArafat: json['busArafat'] as String?,
  busMina: json['busMina'] as String?,
  tentArafat: json['tentArafat'] as String?,
  tentMina: json['tentMina'] as String?,
  phoneNumber: json['phoneNumber'] as String?,
  whatsappNumber: json['whatsappNumber'] as String?,
  syrianPhoneNumber: json['syrianPhoneNumber'] as String?,
  notes: json['notes'] as String?,
);

Map<String, dynamic> _$PilgrimToJson(_Pilgrim instance) => <String, dynamic>{
  'profileId': instance.profileId,
  'displayName': instance.displayName,
  'fieldStatus': instance.fieldStatus,
  'medicalTestStatus': instance.medicalTestStatus,
  'travelDate': instance.travelDate?.toIso8601String(),
  'hotelName': instance.hotelName,
  'hotelLocationUrl': instance.hotelLocationUrl,
  'transportationDetails': instance.transportationDetails,
  'travelPermitNumber': instance.travelPermitNumber,
  'id': instance.id,
  'koboId': instance.koboId,
  'enrollmentId': instance.enrollmentId,
  'pilgrimId': instance.pilgrimId,
  'tripId': instance.tripId,
  'tripType': instance.tripType,
  'groupId': instance.groupId,
  'sequence': instance.sequence,
  'cluster': instance.cluster,
  'coordinatorName': instance.coordinatorName,
  'stickerNumber': instance.stickerNumber,
  'visaNumber': instance.visaNumber,
  'barcodeNumber': instance.barcodeNumber,
  'fullNameAr': instance.fullNameAr,
  'motherNameAr': instance.motherNameAr,
  'birthDate': instance.birthDate,
  'firstNameEn': instance.firstNameEn,
  'lastNameEn': instance.lastNameEn,
  'fatherNameEn': instance.fatherNameEn,
  'motherNameEn': instance.motherNameEn,
  'passportNumber': instance.passportNumber,
  'passportExpiryDate': instance.passportExpiryDate,
  'passportIssueDate': instance.passportIssueDate,
  'gender': instance.gender,
  'bodySize': instance.bodySize,
  'groupName': instance.groupName,
  'companionName': instance.companionName,
  'relation': instance.relation,
  'requestType': instance.requestType,
  'housingType': instance.housingType,
  'hadyStatus': instance.hadyStatus,
  'residence': instance.residence,
  'healthStatus': instance.healthStatus,
  'needsWheelchair': instance.needsWheelchair,
  'isSmoking': instance.isSmoking,
  'healthCard': instance.healthCard,
  'isVaccinated': instance.isVaccinated,
  'makkahHotel': instance.makkahHotel,
  'makkahFloor': instance.makkahFloor,
  'makkahRoom': instance.makkahRoom,
  'madinahTravelDate': instance.madinahTravelDate,
  'madinahHotel': instance.madinahHotel,
  'madinahFloor': instance.madinahFloor,
  'madinahRoom': instance.madinahRoom,
  'departureAirport': instance.departureAirport,
  'departureAirline': instance.departureAirline,
  'departureFlightNo': instance.departureFlightNo,
  'departureDate': instance.departureDate,
  'departureTime': instance.departureTime,
  'returnAirport': instance.returnAirport,
  'returnAirline': instance.returnAirline,
  'returnFlightNo': instance.returnFlightNo,
  'returnDate': instance.returnDate,
  'returnTime': instance.returnTime,
  'serviceCenterName': instance.serviceCenterName,
  'serviceCenterArafat': instance.serviceCenterArafat,
  'serviceCenterMina': instance.serviceCenterMina,
  'busArafat': instance.busArafat,
  'busMina': instance.busMina,
  'tentArafat': instance.tentArafat,
  'tentMina': instance.tentMina,
  'phoneNumber': instance.phoneNumber,
  'whatsappNumber': instance.whatsappNumber,
  'syrianPhoneNumber': instance.syrianPhoneNumber,
  'notes': instance.notes,
};
